### ISSUE TITLE
libmirsdrapi-rsp.so not found, missing entry in list.

### ISSUE THREAD

**Issue by sm3ulc** [rtmrtmrtmrtm/weakmon#3]
In sdrplay.py line 49-, pse add for the generic libname/link: ("libmirsdrapi-rsp.so")

        names = [
            "/usr/local/lib/libmirsdrapi-rsp.so.1.95",
            "libmirsdrapi-rsp.so.1.95",
            "libmirsdrapi-rsp.so",
            "./libmirsdrapi-rsp.so.1.95",
            ]

**Comment by rtmrtmrtmrtm** [comment]
Done.
